### ISSUE TITLE
Issues for https://github.com/RaymondMcGuire/GPU-Based-Image-Processing-Tools

### ISSUE THREAD

**Issue by hjm1fb** [RaymondMcGuire/BOOK-CONTENT-SEGMENTATION-AND-DEWARPING#2]
Hello, I didn't see the issues port on project https://github.com/RaymondMcGuire/GPU-Based-Image-Processing-Tools
So I post it here.
As I read the paper XDoG: Advanced Image Stylization with eXtended Difference-of-Gaussians
http://holgerweb.net/PhD/Research/papers/DoGToonNPAR11.pdf
I noticed the author mentions the performance tip of separating Dog operator into x and y axis（1D dimension） operators, to down scale the computation amount. So have you tried this trick or wanna try? I am very interested in this performance approach, with the intention to run the DoG Stylized effect on most mobile devices without the janky experience. Hope to get some suggestions/pseudocode/ or hopefully Demo from you . Thanks~
Early to wish you: Merry Christmas!

**Comment by RaymondMcGuire** [comment]
> 

I'm very sorry for just noticing this message. As I've been busy with my internship and research lately, I may not have much time to improve the performance of this project soon. Thank you for your suggestion! I will include it in plans for this project.
